version: '3.8'

services:
  db:
    image: postgres:15
    container_name: reservation_db
    restart: always
    environment:
      POSTGRES_USER: reservation_user
      POSTGRES_PASSWORD: reservation_pass
      POSTGRES_DB: reservation_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'shared_preload_libraries=pg_stat_statements'

volumes:
  postgres_data: